AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  InlineLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      PackageType: Zip
      InlineCode: |
        def handle(event, context):
          message = 'Hello {} {}!'.format(event['first_name'], event['last_name'])
          return {
              'message': message
          }