#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "VPC ID not provided."
else
    export VPC_ID="$1"
fi

if [ -z "$2" ]; then
    echo "Internget Gateway ID not provided."
else
    export IGW_ID="$2"
fi

if [ -z "$3" ]; then
    echo "Subnet ID not provided."
else
    export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
    echo "Route Table ID not provided."
else
    export RT_ID="$4"
fi

# Detach IGW
aws ec2 detach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

# DELETE IGW
aws ec2 delete-internet-gateway \
--internet-gateway-id $IGW_ID

# Delete Subnet
aws ec2 delete-subnet \
--subnet-id $SUBNET_ID

# Delete Route Table

aws ec2 delete-route-table \
--route-table-id $RT_ID

# Delete vpc
aws ec2 delete-vpc \
--vpc-id $VPC_ID